services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./images:/var/www/html/images
    ports:
      - 80:80
    depends_on:
      - app

  app:
    # image: registry.gitlab.com/anhpt97/nest-starter
    build: .
    # command: yarn start:dev
    env_file: .env
    ports:
      - 3000:${PORT}
    volumes:
      # - .:/app
      - ./logs:/app/logs
    depends_on:
      - db

  db:
    image: mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    # volumes:
    #   - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - 3306:${DB_PORT}
