name: Deploy

on: workflow_dispatch

jobs:
  build:
    uses: ./.github/workflows/ci.yml
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        env:
          # CR_PAT: ${{ secrets.CR_PAT }}
          EC2_PUBLIC_IP_ADDRESS: ${{ secrets.EC2_PUBLIC_IP_ADDRESS }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
          REGISTRY_IMAGE: ${{ secrets.REGISTRY_IMAGE }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          # USERNAME: ${{ secrets.USERNAME }}
        run: |
          mkdir ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh-keyscan $EC2_PUBLIC_IP_ADDRESS > ~/.ssh/known_hosts
          : # ssh $EC2_USERNAME@$EC2_PUBLIC_IP_ADDRESS "echo $CR_PAT | docker login ghcr.io -u $USERNAME --password-stdin"
          ssh $EC2_USERNAME@$EC2_PUBLIC_IP_ADDRESS "docker pull $REGISTRY_IMAGE"
          ssh $EC2_USERNAME@$EC2_PUBLIC_IP_ADDRESS "docker compose up -d"
          ssh $EC2_USERNAME@$EC2_PUBLIC_IP_ADDRESS "docker system prune -f"
